#!/bin/sh
# Git (prepare-)commit message hook for adding ticket/issue numbers.

MESSAGE_FILE="$1"

for REF in @{u} HEAD; do
    TICKET=$(git rev-parse --abbrev-ref "$REF" 2> /dev/null \
        | grep -oP '\b\w+-\d+$')

    if [ -n "$TICKET" ]; then
        if [ "$(basename "$0")" = "prepare-commit-msg" ]; then
            echo "# Ticket: $TICKET" >> "$MESSAGE_FILE"
            echo "#" >> "$MESSAGE_FILE"
        elif grep -qvP "^\s*(#|$)" "$MESSAGE_FILE"; then
            sed -i.bak -e "1s/^/[$TICKET] /" "$MESSAGE_FILE"
        fi

        break
    fi
done
