#!/bin/bash

dist=$1

if [ -z "$dist" ]; then
    echo "Arguments: <distribution>" >&2
    echo "Example: squeeze" >&2
    exit 1
fi

chroot_dir="/var/chroot/$dist"
debian_sys_url=http://ftp.debian.org/debian/

sudoers_file="/etc/sudoers.d/chroot-$(whoami)"
no_pwd_entry="$(whoami) ALL=NOPASSWD: $(which chroot)"

fs_file=/etc/fstab
home_mount="/home $chroot_dir/home none bind,auto 0 0"
tmp_mount="/tmp $chroot_dir/tmp none bind,auto 0 0"
dev_mount="/dev $chroot_dir/dev none bind,auto 0 0"
proc_mount="proc $chroot_dir/proc proc defaults 0 0"

set -e
sudo mkdir -p -v "$chroot_dir"

if [ ! -f "$sudoers_file" ]; then
    echo '* Adding sudoers entry for password-less chroot.'
    sudo su -c "echo '$no_pwd_entry' > '$sudoers_file'"
fi

if [ ! -d "$chroot_dir/debootstrap" ]; then
    sudo debootstrap --keep-debootstrap-dir \
        "$dist" "$chroot_dir" "$debian_sys_url"
fi

for mount in "$home_mount" "$tmp_mount" "$dev_mount" "$proc_mount"; do
    if ! fgrep -q "$mount" "$fs_file"; then
        echo "* Adding fstab entry for mount point: $mount"
        sudo su -c "echo -e '\n$mount' >> '$fs_file'" || exit 1
    else
        # Ensure it's correctly mounted.
        umount -v "$(echo "$mount" | cut -d' ' -f2)" || true
    fi
done

for path in /etc/{passwd,shadow,group,gshadow,sudoers,hosts}; do
    sudo ln -b -v "$(readlink -e "$path")" "$chroot_dir/$path"
done

sudo cp -b -v {,$chroot_dir}/etc/resolv.conf
sudo mount -a -v
sudo apt-get install -y debootstrap

sudo chroot "$chroot_dir" "$SHELL" -c \
    'apt-get update; apt-get install -y --force-yes sudo locales'

echo "* Ready: $ sudo chroot '$chroot_dir' \$SHELL -c \"su \$(whoami)\""
