import os, SConsX


env = Environment(
    CPPDEFINES = {'PUBLIC_API': 'PUBLIC_EXPORT'},
    CPPPATH = os.environ['NP_API_SDK_INCLUDE_PATH'].split(os.pathsep),
    SHLIBPREFIX = 'np')

files = Glob('*.cpp')
tool = env.BuildTool()[0]

if tool == 'GNU':
    env.Append(CCFLAGS = [
        '-ansi',
        '-pedantic-errors',
        '-Wall',
        '-Weffc++',
        #'-Wextra',
        '-Wold-style-cast',
        '-Wredundant-decls',
        '-Wshadow',
        '-Wswitch-default',
        #'-Wundef',
        '-Wunused-macros',
    ])
elif tool == 'MSVC':
    files += env.RES(Glob('*.rc'))
    env.Append(CPPDEFINES = ['_WINDOWS', '_X86_', 'WIN32'])
    env.Append(CCFLAGS = ['/EHsc', '/MD'])

[library] = env.SharedLibrary(
    target = 'Purple',
    source = files,
    LIBS = ['dl'])

if tool == 'MSVC':
    env.EmbedManifest(library)
