# -*- coding: UTF-8 -*-


# Standard:
from __future__ import absolute_import, division, unicode_literals

# Internal:
#import show as lib


env = Environment(tools = ['default', 'cython', 'find', 'pep8', 'pylint',
    'pyprofile', 'pyunit', 'travis-lint', 'virtualenv'])

src = env.Find('sources')

env.Alias('verify', [
    env.Alias('check', [
        env.TravisLint(),
        env.Pep8(root = src, config = env.Find('pep8.ini')),
        env.Pylint(root = src, config = env.Find('pylint.ini'))]),
    
    env.Alias('test', env.PyUnit(root = src))])

env.Alias('compile',
    env.Cython('show.c', env.Find('show.py'),
        is_standalone = True,
        do_compilation = True))

#env.Profile(source = lambda args: lib.Options.from_cmdl_args(args))

env.Default('compile')
